[[material]]
eos_data = """
*EOS_GRUNEISEN_TITLE
Stainless Steel 304
$--------1---------2---------3---------4---------5---------6---------7---------8
$#   EOSID         C        S1        S2        S3    GAMMAO         A        E0
"""
app = ["Test"]
url = "http://example.com"