name: 🧪 Material Submission
description: Submit a new LS-DYNA material model
title: "[MATERIAL] "
labels: ["material-submission"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing to MaterialMap! Please fill out the form below to submit a new material model.
        
        **Note:** All fields marked with * are required.

  - type: input
    id: material_name
    attributes:
      label: Material Name *
      description: Name of the material (e.g., "Steel AISI 4340", "Aluminum 6061-T6")
      placeholder: ex. Steel AISI 4340
    validations:
      required: true

  - type: input
    id: material_id
    attributes:
      label: LS-DYNA Material ID *
      description: Enter the LS-DYNA material model ID (e.g., MAT_015, MAT_024, MAT_107)
      placeholder: ex. MAT_015
    validations:
      required: true

  - type: textarea
    id: material_data
    attributes:
      label: Material Data *
      description: Paste the LS-DYNA material card data here
      placeholder: |
        *MAT_JOHNSON_COOK_TITLE
        Steel AISI 4340
        $--------1---------2---------3---------4---------5---------6---------7---------8
        $#     MID        RO         E        PR       DTF        VP    RATEOP
             15     7.83e-9    200000      0.29         0         0         0
        ...
      render: text
    validations:
      required: true

  - type: input
    id: eos_model
    attributes:
      label: Equation of State (EOS)
      description: Enter EOS model if applicable (leave empty if not used)
      placeholder: ex. EOS_GRUNEISEN, EOS_LINEAR_POLYNOMIAL

  - type: textarea
    id: eos_data
    attributes:
      label: EOS Data
      description: Paste EOS data if applicable
      placeholder: |
        *EOS_GRUNEISEN_TITLE
        Steel AISI 4340
        $#   EOSID         C        S1        S2        S3    GAMMAO         A        E0
             15    0.4610      1.73         0         0      2.17         0         0
      render: text

  - type: textarea
    id: applications
    attributes:
      label: Applications *
      description: List applications/use cases (one per line)
      placeholder: |
        High-strength steel applications
        Automotive components
        Ballistic applications
    validations:
      required: true

  - type: input
    id: reference
    attributes:
      label: Reference *
      description: Full citation of the source paper/document
      placeholder: ex. Smith, J. et al. (2023). Material characterization of AISI 4340 steel. Journal of Materials, 15(3), 123-145.
    validations:
      required: true

  - type: input
    id: reference_url
    attributes:
      label: Reference URL *
      description: Link to the source (must be open access)
      placeholder: https://doi.org/10.1000/example
    validations:
      required: true

  - type: textarea
    id: additional_info
    attributes:
      label: Additional Information
      description: Any additional notes or context about this material
      placeholder: Special notes, validation data, limitations, etc.

  - type: checkboxes
    id: terms
    attributes:
      label: Submission Requirements
      description: Please confirm the following
      options:
        - label: The source is published under Open Access license
          required: true
        - label: I have verified the material parameters are correct
          required: true
        - label: The reference URL is accessible without paywall
          required: true