backend:
  name: git-gateway
  branch: main

# Local development configuration
local_backend: true

# Media files configuration
media_folder: "assets/uploads"
public_folder: "/assets/uploads"

# Collections configuration
collections:
  - name: "materials"
    label: "Material Models"
    label_singular: "Material Model"
    folder: "data"
    create: true
    delete: true
    extension: "yaml"
    format: "yaml"
    slug: "{{fields.0.material.ref}}-{{year}}"
    identifier_field: "0.material.ref"
    editor:
      preview: false
    fields:
      - label: "Materials"
        name: "materials"
        widget: "list"
        summary: "{{fields.material.id}} - {{fields.material.mat}}"
        fields:
          - label: "Material"
            name: "material"
            widget: "object"
            fields:
              - label: "ID"
                name: "id"
                widget: "string"
                required: true
                hint: "LS-DYNA material ID (e.g., MAT_240)"
              - label: "Material Type"
                name: "mat"
                widget: "select"
                required: true
                options:
                  - "MAT_COHESIVE_MIXED_MODE_ELASTOPLASTIC_RATE"
                  - "MAT_CSCM"
                  - "MAT_NON_QUADRATIC_FAILURE"
                  - "MAT_JOHNSON_COOK"
                  - "MAT_MODIFIED_JOHNSON_COOK"
                  - "MAT_PLASTIC_KINEMATIC"
                  - "MAT_ELASTIC"
                  - "MAT_RIGID"
                  - "MAT_HONEYCOMB"
                  - "MAT_CRUSHABLE_FOAM"
                  - "MAT_CONCRETE_DAMAGE"
                  - "MAT_MOHR_COULOMB"
                  - "MAT_SOIL_AND_FOAM"
                  - "MAT_WINFRITH_CONCRETE"
                  - "MAT_CONCRETE_DAMAGE_REL3"
                  - "MAT_CSCM_CONCRETE"
                  - "MAT_JOHNSON_HOLMQUIST_CONCRETE"
                  - "MAT_JOHNSON_HOLMQUIST_CERAMICS"
                  - "MAT_STEINBERG_GUINAN"
                  - "MAT_ZERILLI_ARMSTRONG"
                  - "MAT_COWPER_SYMONDS"
                  - "MAT_POWER_LAW_PLASTICITY"
                  - "MAT_STRAIN_RATE_DEPENDENT_PLASTICITY"
                  - "MAT_PIECEWISE_LINEAR_PLASTICITY"
                  - "MAT_BILINEAR_KINEMATIC"
                  - "MAT_ORTHOTROPIC_ELASTIC"
                  - "MAT_ANISOTROPIC_ELASTIC"
                  - "MAT_VISCOELASTIC"
                  - "MAT_KELVIN_MAXWELL_VISCOELASTIC"
                  - "MAT_DAMPER_VISCOUS"
                  - "MAT_SPRING_ELASTIC"
                  - "MAT_SPRING_NONLINEAR_ELASTIC"
                  - "MAT_SPRING_GENERAL_NONLINEAR"
                  - "MAT_FABRIC"
                  - "MAT_LAMINATED_COMPOSITE_FABRIC"
                  - "MAT_ENHANCED_COMPOSITE_DAMAGE"
                  - "MAT_COMPOSITE_DAMAGE"
                  - "MAT_COMPOSITE_FAILURE_SOLID"
                  - "MAT_COMPOSITE_FAILURE_SHELL"
                  - "MAT_COMPOSITE_MSC"
                  - "MAT_LAMINATED_GLASS"
                  - "MAT_ELASTIC_PLASTIC_HYDRO"
                allow_add: true
                hint: "LS-DYNA material model type"
              - label: "EOS"
                name: "eos"
                widget: "string"
                required: false
                hint: "Equation of State (if applicable)"
              - label: "Applications"
                name: "app"
                widget: "list"
                required: true
                field: 
                  label: "Application"
                  name: "application"
                  widget: "string"
                hint: "List of material applications"
              - label: "Material Data"
                name: "mat_data"
                widget: "code"
                default_language: "text"
                allow_language_selection: false
                required: false
                hint: "LS-DYNA material card data"
              - label: "EOS Data"
                name: "eos_data"
                widget: "code"
                default_language: "text"
                allow_language_selection: false
                required: false
                hint: "LS-DYNA EOS card data"
              - label: "Reference"
                name: "ref"
                widget: "string"
                required: false
                hint: "Reference citation"
              - label: "URL"
                name: "url"
                widget: "string"
                required: false
                hint: "Source URL"
              - label: "Date Added"
                name: "add"
                widget: "datetime"
                date_format: "YYYY-MM-DD"
                time_format: false
                required: true
                default: ""
                hint: "Date when this material was added"

# Site configuration
site_url: http://127.0.0.1:5500
display_url: http://127.0.0.1:5500

# Search configuration
search: true